CREATE TABLE tb_reserva (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    data_reserva DATE,
    data_expiracao DATE,
    data_disponivel DATE,

    status VARCHAR(50) NOT NULL,

    user_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,

    CONSTRAINT fk_reserva_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user(id),

    CONSTRAINT fk_reserva_livro
        FOREIGN KEY (livro_id)
            REFERENCES tb_livro(id)
);