-- ============================================================
-- V12: Criação da tabela tb_exemplar + coluna exemplar_id em
--      tb_emprestimo + migração retroativa de dados existentes
-- ============================================================

-- 1) Cria a tabela de exemplares
CREATE TABLE tb_exemplar (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo  VARCHAR(10)  NOT NULL,
    status  VARCHAR(20)  NOT NULL DEFAULT 'DISPONIVEL',
    livro_id BIGINT NOT NULL,

    CONSTRAINT fk_exemplar_livro
        FOREIGN KEY (livro_id) REFERENCES tb_livro(id)
);

CREATE INDEX idx_exemplar_livro_id ON tb_exemplar(livro_id);
CREATE INDEX idx_exemplar_status   ON tb_exemplar(status);

-- 2) Adiciona coluna exemplar_id em tb_emprestimo (nullable para não quebrar dados antigos)
ALTER TABLE tb_emprestimo
    ADD COLUMN exemplar_id BIGINT,
    ADD CONSTRAINT fk_emprestimo_exemplar
        FOREIGN KEY (exemplar_id) REFERENCES tb_exemplar(id);

-- 3) Gera exemplares retroativamente para cada livro existente
--    Lógica:
--      - total_exemplares copias são criadas com códigos 001, 002, ...
--      - (total_exemplares - quantidade_Disponivel) primeiros ficam como EMPRESTADO
--      - o restante fica como DISPONIVEL
DO $$
DECLARE
    livro_rec   RECORD;
    i           INTEGER;
    total       INTEGER;
    disponiveis INTEGER;
    emprestados INTEGER;
    ex_status   VARCHAR(20);
BEGIN
    FOR livro_rec IN
        SELECT id, total_exemplares, quantidade_disponivel
        FROM tb_livro
    LOOP
        total       := COALESCE(livro_rec.total_exemplares, 0);
        disponiveis := COALESCE(livro_rec.quantidade_disponivel, 0);
        emprestados := GREATEST(total - disponiveis, 0);

        FOR i IN 1..total LOOP
            IF i <= emprestados THEN
                ex_status := 'EMPRESTADO';
            ELSE
                ex_status := 'DISPONIVEL';
            END IF;

            INSERT INTO tb_exemplar (codigo, status, livro_id)
            VALUES (LPAD(i::TEXT, 3, '0'), ex_status, livro_rec.id);
        END LOOP;
    END LOOP;
END $$;

-- 4) Vincula empréstimos ATIVO/ATRASADO existentes ao primeiro exemplar EMPRESTADO disponível
--    (sem FK duplicada — cada exemplar só pode ter um empréstimo ativo)
DO $$
DECLARE
    emp_rec RECORD;
    ex_id   BIGINT;
BEGIN
    FOR emp_rec IN
        SELECT id, livro_id
        FROM tb_emprestimo
        WHERE status IN ('ATIVO', 'ATRASADO')
        ORDER BY id
    LOOP
        SELECT ex.id INTO ex_id
        FROM tb_exemplar ex
        WHERE ex.livro_id = emp_rec.livro_id
          AND ex.status   = 'EMPRESTADO'
          AND ex.id NOT IN (
              SELECT exemplar_id
              FROM tb_emprestimo
              WHERE exemplar_id IS NOT NULL
          )
        ORDER BY ex.codigo
        LIMIT 1;

        IF ex_id IS NOT NULL THEN
            UPDATE tb_emprestimo
            SET exemplar_id = ex_id
            WHERE id = emp_rec.id;
        END IF;
    END LOOP;
END $$;
