CREATE TABLE tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT fk_usuario_role
        FOREIGN KEY (role_id)
            REFERENCES tb_roles(id)
);