CREATE TABLE tb_emprestimo (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    data_emprestimo DATE,
    data_devolucao DATE,
    data_devolvido DATE,

    renovacoes INTEGER DEFAULT 0,

    status VARCHAR(50) NOT NULL,

    user_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,

    CONSTRAINT fk_emprestimo_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user(id),

    CONSTRAINT fk_emprestimo_livro
        FOREIGN KEY (livro_id)
            REFERENCES tb_livro(id)
);